/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package trafficflow.ctm.tf_devs.datasource;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Tf_Devs extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4849383759559924784L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Tf_Devs\",\"namespace\":\"trafficflow.ctm.tf_devs.datasource\",\"fields\":[{\"name\":\"data\",\"type\":{\"type\":\"record\",\"name\":\"Data\",\"fields\":[{\"name\":\"locations\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Location_record\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"sensorName\",\"type\":\"string\"},{\"name\":\"position\",\"type\":{\"type\":\"record\",\"name\":\"Position\",\"fields\":[{\"name\":\"coordinates\",\"type\":{\"type\":\"array\",\"items\":\"float\"}},{\"name\":\"type\",\"type\":\"string\"}]}},{\"name\":\"symbol\",\"type\":[\"null\",\"string\"]}]}}}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Tf_Devs> ENCODER =
      new BinaryMessageEncoder<Tf_Devs>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Tf_Devs> DECODER =
      new BinaryMessageDecoder<Tf_Devs>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Tf_Devs> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Tf_Devs> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Tf_Devs> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Tf_Devs>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Tf_Devs to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Tf_Devs from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Tf_Devs instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Tf_Devs fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private trafficflow.ctm.tf_devs.datasource.Data data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Tf_Devs() {}

  /**
   * All-args constructor.
   * @param data The new value for data
   */
  public Tf_Devs(trafficflow.ctm.tf_devs.datasource.Data data) {
    this.data = data;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return data;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: data = (trafficflow.ctm.tf_devs.datasource.Data)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public trafficflow.ctm.tf_devs.datasource.Data getData() {
    return data;
  }


  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(trafficflow.ctm.tf_devs.datasource.Data value) {
    this.data = value;
  }

  /**
   * Creates a new Tf_Devs RecordBuilder.
   * @return A new Tf_Devs RecordBuilder
   */
  public static trafficflow.ctm.tf_devs.datasource.Tf_Devs.Builder newBuilder() {
    return new trafficflow.ctm.tf_devs.datasource.Tf_Devs.Builder();
  }

  /**
   * Creates a new Tf_Devs RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Tf_Devs RecordBuilder
   */
  public static trafficflow.ctm.tf_devs.datasource.Tf_Devs.Builder newBuilder(trafficflow.ctm.tf_devs.datasource.Tf_Devs.Builder other) {
    if (other == null) {
      return new trafficflow.ctm.tf_devs.datasource.Tf_Devs.Builder();
    } else {
      return new trafficflow.ctm.tf_devs.datasource.Tf_Devs.Builder(other);
    }
  }

  /**
   * Creates a new Tf_Devs RecordBuilder by copying an existing Tf_Devs instance.
   * @param other The existing instance to copy.
   * @return A new Tf_Devs RecordBuilder
   */
  public static trafficflow.ctm.tf_devs.datasource.Tf_Devs.Builder newBuilder(trafficflow.ctm.tf_devs.datasource.Tf_Devs other) {
    if (other == null) {
      return new trafficflow.ctm.tf_devs.datasource.Tf_Devs.Builder();
    } else {
      return new trafficflow.ctm.tf_devs.datasource.Tf_Devs.Builder(other);
    }
  }

  /**
   * RecordBuilder for Tf_Devs instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Tf_Devs>
    implements org.apache.avro.data.RecordBuilder<Tf_Devs> {

    private trafficflow.ctm.tf_devs.datasource.Data data;
    private trafficflow.ctm.tf_devs.datasource.Data.Builder dataBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(trafficflow.ctm.tf_devs.datasource.Tf_Devs.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasDataBuilder()) {
        this.dataBuilder = trafficflow.ctm.tf_devs.datasource.Data.newBuilder(other.getDataBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Tf_Devs instance
     * @param other The existing instance to copy.
     */
    private Builder(trafficflow.ctm.tf_devs.datasource.Tf_Devs other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
      this.dataBuilder = null;
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public trafficflow.ctm.tf_devs.datasource.Data getData() {
      return data;
    }


    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public trafficflow.ctm.tf_devs.datasource.Tf_Devs.Builder setData(trafficflow.ctm.tf_devs.datasource.Data value) {
      validate(fields()[0], value);
      this.dataBuilder = null;
      this.data = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'data' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public trafficflow.ctm.tf_devs.datasource.Data.Builder getDataBuilder() {
      if (dataBuilder == null) {
        if (hasData()) {
          setDataBuilder(trafficflow.ctm.tf_devs.datasource.Data.newBuilder(data));
        } else {
          setDataBuilder(trafficflow.ctm.tf_devs.datasource.Data.newBuilder());
        }
      }
      return dataBuilder;
    }

    /**
     * Sets the Builder instance for the 'data' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public trafficflow.ctm.tf_devs.datasource.Tf_Devs.Builder setDataBuilder(trafficflow.ctm.tf_devs.datasource.Data.Builder value) {
      clearData();
      dataBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'data' field has an active Builder instance
     * @return True if the 'data' field has an active Builder instance
     */
    public boolean hasDataBuilder() {
      return dataBuilder != null;
    }

    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public trafficflow.ctm.tf_devs.datasource.Tf_Devs.Builder clearData() {
      data = null;
      dataBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Tf_Devs build() {
      try {
        Tf_Devs record = new Tf_Devs();
        if (dataBuilder != null) {
          try {
            record.data = this.dataBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("data"));
            throw e;
          }
        } else {
          record.data = fieldSetFlags()[0] ? this.data : (trafficflow.ctm.tf_devs.datasource.Data) defaultValue(fields()[0]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Tf_Devs>
    WRITER$ = (org.apache.avro.io.DatumWriter<Tf_Devs>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Tf_Devs>
    READER$ = (org.apache.avro.io.DatumReader<Tf_Devs>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.data.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.data == null) {
        this.data = new trafficflow.ctm.tf_devs.datasource.Data();
      }
      this.data.customDecode(in);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.data == null) {
            this.data = new trafficflow.ctm.tf_devs.datasource.Data();
          }
          this.data.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










